/**
 * Cipher Torrent Client API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TorrentSignature { 
    signer_user_id: number;
    signer_public_key: string;
    signature_bytes: string;
    is_valid: boolean;
    signed_at: string;
}

