/*
 * Cipher Torrent Client API
 *
 * REST API для управления узлом Cipher Torrent. ## Real-time Events (WebSocket) Для обеспечения реактивности интерфейса, клиент должен установить WebSocket-соединение с сервером по адресу: `ws://localhost:8080/api/v1/ws` Сервер будет асинхронно пушить в этот канал события в виде JSON. Поддерживаемые типы событий (описаны в схемах): * `torrent:progress` -> **TorrentProgressEvent** (Динамическое изменение скорости и прогресса) * `torrent:signed` -> **TorrentSignedEvent** (Обнаружение новой криптографической подписи в сети) * `peer:connected` -> **PeerConnectedEvent** (Подключение нового узла) * `reputation:update` -> **ReputationUpdateEvent** (Изменение Web of Trust) * `packet` -> **PacketEvent** (Сырой дамп трафика для инспектора)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package packet

import (
	"github.com/AlexKalinckovich/Cipher-Torrent-Client/backend/model/reputation"
	"time"
)

type PacketLog struct {
	Id int64 `json:"id"`

	Timestamp time.Time `json:"timestamp"`

	Direction string `json:"direction"`

	MessageType string `json:"message_type"`

	PeerIp string `json:"peer_ip,omitempty"`

	RawPayloadBase64 string `json:"raw_payload_base64"`

	ParsedInfo string `json:"parsed_info,omitempty"`

	ReputationPayload reputation.ReputationReceipt `json:"reputation_payload,omitempty"`

	SizeBytes int32 `json:"size_bytes,omitempty"`
}
