/**
 * Cipher Torrent Client API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReputationReceipt { 
    from_peer_id: string;
    to_peer_id: string;
    piece_index: number;
    byte_count: number;
    signature: string;
    timestamp: string;
}

