/*
 * Cipher Torrent Client API
 *
 * REST API для управления узлом Cipher Torrent. ## Real-time Events (WebSocket) Для обеспечения реактивности интерфейса, клиент должен установить WebSocket-соединение с сервером по адресу: `ws://localhost:8080/api/v1/ws` Сервер будет асинхронно пушить в этот канал события в виде JSON. Поддерживаемые типы событий (описаны в схемах): * `torrent:progress` -> **TorrentProgressEvent** (Динамическое изменение скорости и прогресса) * `torrent:signed` -> **TorrentSignedEvent** (Обнаружение новой криптографической подписи в сети) * `peer:connected` -> **PeerConnectedEvent** (Подключение нового узла) * `reputation:update` -> **ReputationUpdateEvent** (Изменение Web of Trust) * `packet` -> **PacketEvent** (Сырой дамп трафика для инспектора)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package torrent

import (
	"time"
)

type Torrent struct {
	Id int64 `json:"id"`

	InfoHash string `json:"info_hash"`

	Name string `json:"name"`

	SizeBytes int64 `json:"size_bytes"`

	Status string `json:"status"`

	Progress float32 `json:"progress,omitempty"`

	DownloadSpeedBps int64 `json:"download_speed_bps,omitempty"`

	UploadSpeedBps int64 `json:"upload_speed_bps,omitempty"`

	AddedAt time.Time `json:"added_at"`

	PieceLength int64 `json:"piece_length,omitempty"`

	Files []TorrentFile `json:"files,omitempty"`

	SignaturesCount int32 `json:"signatures_count,omitempty"`

	IsSignedByMe bool `json:"is_signed_by_me,omitempty"`

	PeersCount int32 `json:"peers_count,omitempty"`
}
