/**
 * Cipher Torrent Client API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Cipher Torrent Client API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type {PeerFlags} from './peerFlags';


export interface Peer { 
    peer_id: string;
    ip: string;
    port: number;
    client_name: string;
    supports_ut_reputation: boolean;
    reputation_score?: number;
    last_seen?: string;
    connected_since?: string;
    download_speed_bps?: number;
    upload_speed_bps?: number;
    flags?: PeerFlags;
}

