/*
 * Cipher Torrent Client API
 *
 * REST API для управления узлом Cipher Torrent. ## Real-time Events (WebSocket) Для обеспечения реактивности интерфейса, клиент должен установить WebSocket-соединение с сервером по адресу: `ws://localhost:8080/api/v1/ws` Сервер будет асинхронно пушить в этот канал события в виде JSON. Поддерживаемые типы событий (описаны в схемах): * `torrent:progress` -> **TorrentProgressEvent** (Динамическое изменение скорости и прогресса) * `torrent:signed` -> **TorrentSignedEvent** (Обнаружение новой криптографической подписи в сети) * `peer:connected` -> **PeerConnectedEvent** (Подключение нового узла) * `reputation:update` -> **ReputationUpdateEvent** (Изменение Web of Trust) * `packet` -> **PacketEvent** (Сырой дамп трафика для инспектора)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package reputation

import (
	"time"
)

type ReputationReceipt struct {
	FromPeerId string `json:"from_peer_id"`

	ToPeerId string `json:"to_peer_id"`

	PieceIndex int32 `json:"piece_index"`

	ByteCount int32 `json:"byte_count"`

	Signature string `json:"signature"`

	Timestamp time.Time `json:"timestamp"`
}
