/*
 * Cipher Torrent Client API
 *
 * REST API для управления узлом Cipher Torrent. ## Real-time Events (WebSocket) Для обеспечения реактивности интерфейса, клиент должен установить WebSocket-соединение с сервером по адресу: `ws://localhost:8080/api/v1/ws` Сервер будет асинхронно пушить в этот канал события в виде JSON. Поддерживаемые типы событий (описаны в схемах): * `torrent:progress` -> **TorrentProgressEvent** (Динамическое изменение скорости и прогресса) * `torrent:signed` -> **TorrentSignedEvent** (Обнаружение новой криптографической подписи в сети) * `peer:connected` -> **PeerConnectedEvent** (Подключение нового узла) * `reputation:update` -> **ReputationUpdateEvent** (Изменение Web of Trust) * `packet` -> **PacketEvent** (Сырой дамп трафика для инспектора)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package peer

import (
	"time"
)

type Peer struct {
	PeerId string `json:"peer_id"`

	Ip string `json:"ip"`

	Port int32 `json:"port"`

	ClientName string `json:"client_name"`

	SupportsUtReputation bool `json:"supports_ut_reputation"`

	ReputationScore float32 `json:"reputation_score,omitempty"`

	LastSeen time.Time `json:"last_seen,omitempty"`

	ConnectedSince time.Time `json:"connected_since,omitempty"`

	DownloadSpeedBps int64 `json:"download_speed_bps,omitempty"`

	UploadSpeedBps int64 `json:"upload_speed_bps,omitempty"`

	Flags PeerFlags `json:"flags,omitempty"`
}
