/*
 * Cipher Torrent Client API
 *
 * REST API для управления узлом Cipher Torrent. ## Real-time Events (WebSocket) Для обеспечения реактивности интерфейса, клиент должен установить WebSocket-соединение с сервером по адресу: `ws://localhost:8080/api/v1/ws` Сервер будет асинхронно пушить в этот канал события в виде JSON. Поддерживаемые типы событий (описаны в схемах): * `torrent:progress` -> **TorrentProgressEvent** (Динамическое изменение скорости и прогресса) * `torrent:signed` -> **TorrentSignedEvent** (Обнаружение новой криптографической подписи в сети) * `peer:connected` -> **PeerConnectedEvent** (Подключение нового узла) * `reputation:update` -> **ReputationUpdateEvent** (Изменение Web of Trust) * `packet` -> **PacketEvent** (Сырой дамп трафика для инспектора)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package user

type UserStats struct {
	TotalUploadedBytes int64 `json:"total_uploaded_bytes"`

	TotalDownloadedBytes int64 `json:"total_downloaded_bytes"`

	ReputationScore float32 `json:"reputation_score"`

	SignedTorrentsCount int32 `json:"signed_torrents_count"`

	ActiveTorrentsCount int32 `json:"active_torrents_count"`

	PeersTrustedCount int32 `json:"peers_trusted_count"`
}
