/*
 * Cipher Torrent Client API
 *
 * REST API для управления узлом Cipher Torrent. ## Real-time Events (WebSocket) Для обеспечения реактивности интерфейса, клиент должен установить WebSocket-соединение с сервером по адресу: `ws://localhost:8080/api/v1/ws` Сервер будет асинхронно пушить в этот канал события в виде JSON. Поддерживаемые типы событий (описаны в схемах): * `torrent:progress` -> **TorrentProgressEvent** (Динамическое изменение скорости и прогресса) * `torrent:signed` -> **TorrentSignedEvent** (Обнаружение новой криптографической подписи в сети) * `peer:connected` -> **PeerConnectedEvent** (Подключение нового узла) * `reputation:update` -> **ReputationUpdateEvent** (Изменение Web of Trust) * `packet` -> **PacketEvent** (Сырой дамп трафика для инспектора)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the DefaultAPI part of the API
	DefaultAPI DefaultAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{
		{
			"AddTorrent",
			http.MethodPost,
			"/api/v1/torrents",
			handleFunctions.DefaultAPI.AddTorrent,
		},
		{
			"GetMyProfile",
			http.MethodGet,
			"/api/v1/users/me",
			handleFunctions.DefaultAPI.GetMyProfile,
		},
		{
			"GetTorrent",
			http.MethodGet,
			"/api/v1/torrents/:infoHash",
			handleFunctions.DefaultAPI.GetTorrent,
		},
		{
			"GetTorrentPeers",
			http.MethodGet,
			"/api/v1/torrents/:infoHash/peers",
			handleFunctions.DefaultAPI.GetTorrentPeers,
		},
		{
			"GetTorrentSignatures",
			http.MethodGet,
			"/api/v1/torrents/:infoHash/signatures",
			handleFunctions.DefaultAPI.GetTorrentSignatures,
		},
		{
			"GetTorrents",
			http.MethodGet,
			"/api/v1/torrents",
			handleFunctions.DefaultAPI.GetTorrents,
		},
		{
			"LoginUser",
			http.MethodPost,
			"/api/v1/auth/login",
			handleFunctions.DefaultAPI.LoginUser,
		},
		{
			"PauseTorrent",
			http.MethodPost,
			"/api/v1/torrents/:infoHash/pause",
			handleFunctions.DefaultAPI.PauseTorrent,
		},
		{
			"RefreshToken",
			http.MethodPost,
			"/api/v1/auth/refresh",
			handleFunctions.DefaultAPI.RefreshToken,
		},
		{
			"RegisterUser",
			http.MethodPost,
			"/api/v1/auth/register",
			handleFunctions.DefaultAPI.RegisterUser,
		},
		{
			"ResumeTorrent",
			http.MethodPost,
			"/api/v1/torrents/:infoHash/resume",
			handleFunctions.DefaultAPI.ResumeTorrent,
		},
		{
			"SignTorrent",
			http.MethodPost,
			"/api/v1/torrents/:infoHash/sign",
			handleFunctions.DefaultAPI.SignTorrent,
		},
	}
}
